### ISSUE TITLE
?filter[name]= removed?

### ISSUE THREAD

**Issue by chriseugenerodriguez** [WP-API/docs#18]
did you remove filter method from your api?

**Comment by demitri** [comment]
It was removed. From the REST API Handbook:

<https://developer.wordpress.org/rest-api/using-the-rest-api/frequently-asked-questions/#what-happened-to-the-filter-query-parameter>

The [rest-filter plug-in](https://github.com/wp-api/rest-filter) can restore the functionality if needed.
