### ISSUE TITLE
Detect changes to content edited on the developer site

### ISSUE THREAD

**Issue by nylen** [WP-API/docs#3]
The obvious way to update e.g. https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/ is to edit the page from within WordPress.  While moving this content into GitHub would allow easier contribution from the community, we need to be careful not to overwrite edits made from within the WP site.

A couple of potential options:

- Somehow detect changes to the content and warn/error before overwriting it.
- Some kind of sync thingy to go from HTML back to Markdown.
- Disable editing via the WP interface.

**Comment by nylen** [comment]
After using the visual editor on the above page and ending up with a bunch of `&amp;amp;lt;`... I vote for option 3.

**Comment by rmccue** [comment]
This should probably be filed on the [Markdown sync](https://github.com/WP-API/markdown-sync) repo.

The [existing code for the CLI handbook](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-cli/inc/class-handbook.php) (not the CLI command reference, which is what this is based on) does some UI work here, as well as [changing the edit screen a bit](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-cli/inc/class-markdown-import.php#L161). On my list to steal that code too. :)

**Comment by rmccue** [comment]
This is now implemented and live on DevHub:

<img width="795" alt="screenshot 2017-11-04 14 32 22" src="https://user-images.githubusercontent.com/21655/32402321-fe484872-c16c-11e7-9478-45e6e7901dff.png">

The Edit Page link in the admin bar/etc links to GitHub, and the page title has an edit button next to it as well. :)
