### ISSUE TITLE
Add "type" support when creating a new post

### ISSUE THREAD

**Issue by jonferreira** [WP-API/docs#35]
Hi,

Would be great to add support for posts "type" when creating a post with POST /wp/v2/posts

According to https://developer.wordpress.org/rest-api/reference/posts/#create-a-post "type" is not supported?

**Comment by rmccue** [comment]
Version 2 of the REST API uses separate endpoints for separate post types, rather than a generic "posts" endpoint for all CPTs.

This is pretty well covered at https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-rest-api-support-for-custom-content-types/ I think?

**Comment by jonferreira** [comment]
Sooooooo easy! - I completely missed that, thanks @rmccue
