### ISSUE TITLE
Chinese Version of wp-api docs

### ISSUE THREAD

**Issue by Zhoukaiqiang** [WP-API/docs#44]
Is there any Chinese version of WP-API docs ? If not ,I hope the WordPress group add a button 
to switch language like Morzilla's MDN, It's hopeful for all Chinese developer. Or anyone can edit it.
Thanks!

**Comment by kadamwhite** [comment]
I agree this would be useful but it is unfortunately currently out of scope for our current team, none of whom speak Chinese. I believe there is at least one community-maintained translation into another language, so I hope to see a Chinese version some day!
