### ISSUE TITLE
"Modifying Responses" page contradicts itself

### ISSUE THREAD

**Issue by narthur** [WP-API/docs#55]
[This section](https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/#using-register_rest_field-vs-register_meta) and [this section](https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/#working-with-registered-meta-in-the-rest-api):

> As of WordPress 4.9.8 it’s possible to use register_meta with the object_subtype argument that allows one to reduce the usage of the meta key to a particular post type.

And:

> The register_meta function simplifies the process of defining a meta field for a particular object type. By setting 'show_in_rest' => true when registering a new meta key, that key will be accessible through the REST API. Note however that at this time there is no way to register a meta field for a specific post type: meta fields registered for the “post” object will appear on all custom post types, as well as the default post record.

I believe the second section referenced needs updating.

**Comment by TimothyBJacobs** [comment]
Thanks for the report @narthur. I believe this has been resolved by #51.
