### ISSUE TITLE
Update documentation for 5.3

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/docs#58]
When 5.3 ships we should update associated documentation. This will be a running list of things we should cover.

- [x] Array & Object Metadata
- [x] `_fields` nesting
- [ ] New media endpoint (with note it's really intended for internal use)
- [ ] Performance?
- [x] Audit tickets to figure out what else is needed ([report of closed tickets](https://core.trac.wordpress.org/query?status=closed&status=reopened&component=REST+API&milestone=5.3&or&keywords=~rest-api&status=closed&status=reopened&milestone=5.3&or&status=closed&status=reopened&focuses=~rest-api&milestone=5.3&col=id&col=summary&col=status&col=milestone&col=component&col=type&col=priority&desc=1&order=id))
- [x] Update Changelog

**Comment by kadamwhite** [comment]
Fields is now documented, see #61

**Comment by TimothyBJacobs** [comment]
I have a WIP for metadata in #69.

**Comment by TimothyBJacobs** [comment]
I think we could document the schema caching performance improvement in `controller-classes.md`? I opened #70 for that.

I think the new media endpoint would get imported when we regenerate the reference? It'd be nice if we could figure out a way to add custom information to those descriptions so we could notate that it is for internal use.

Looking through the tickets, I didn't find any that I think warrant large sections. But these are the ones I think would be good to add to the changelog.

- https://core.trac.wordpress.org/ticket/47871
- https://core.trac.wordpress.org/ticket/47684
- https://core.trac.wordpress.org/ticket/44975
- https://core.trac.wordpress.org/ticket/43709
- https://core.trac.wordpress.org/ticket/43691
- https://core.trac.wordpress.org/ticket/43392
- https://core.trac.wordpress.org/ticket/42094
- https://core.trac.wordpress.org/ticket/41411
- https://core.trac.wordpress.org/ticket/39953

**Comment by kadamwhite** [comment]
Marking as to-be-resolved by #92
