### ISSUE TITLE
Update documentation for 5.4

### ISSUE THREAD

**Issue by TimothyBJacobs** [WP-API/docs#88]
This will serve as a tracking ticket for making documentation changes to account for WordPress 5.4. We should aim to have these done before 5.4 ships on March 31.

- [x] Review [closed tickets in the 5.4 milestone](https://core.trac.wordpress.org/query?status=closed&status=reopened&component=REST+API&milestone=5.4&or&keywords=~rest-api&status=closed&status=reopened&milestone=5.4&or&status=closed&status=reopened&focuses=~rest-api&milestone=5.4&col=id&col=summary&col=status&col=milestone&col=component&col=type&col=priority&desc=1&order=id) to identify what needs special docs handling
- [x] Update the Changelog page
- [ ] Regenerate the reference documentation
- [ ] Document _how_ to regenerate the reference documentation (assigned to @kadamwhite)

**Comment by kadamwhite** [comment]
Last two points covered by #92
